### PR TITLE
[WIP] support npm3

### PR DESCRIPTION
**Pull request by garrensmith**

### CODE REVIEW

**Comment by kxepal** [comment]
> Files changed: 7,615 
O.O

**Comment by garrensmith** [comment]
its because we bundle all the dependencies. So when someone installs nmo they have everything. Don't need to fetch anything and we shouldn't have any dependency version issues.

**Comment by kxepal** [comment]
It's all nice from technical side, but from legal one are all the deps compatible with Apache v2 license and doesn't including them all violates any ASF rule? I'm in doubts.

**Comment by garrensmith** [comment]
Yes. Thats why its [WIP] we have to decide how to manage this. Any suggestions would be great.

**Comment by garrensmith** [comment]
After discussion with @janl and @kxepal we don't need this anymore. I'm closing.

**Pull request closed without merging**
